spring:
  main:
    lazy-initialization: true
  application:
    name: trainguard-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/trainguard}
    username: ${SPRING_DATASOURCE_USERNAME:trainguard_user}
    password: ${SPRING_DATASOURCE_PASSWORD:trainguard_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

strava:
  client-id: ${STRAVA_CLIENT_ID}
  client-secret: ${STRAVA_CLIENT_SECRET}
  refresh-token: ${STRAVA_REFRESH_TOKEN}
  redirect-uri: ${STRAVA_REDIRECT_URI:http://localhost:8080/api/strava/callback}
  webhook:
    verify-token: ${STRAVA_WEBHOOK_VERIFY_TOKEN:local-smart-gauge-webhook-token}
train-guard:
  app-redirect-uri: ${TRAIN_GUARD_APP_REDIRECT_URI:http://localhost:8081/strava-connected}
