spring:
  application:
    name: trainguard-backend

  datasource:
    url: jdbc:postgresql://localhost:5435/trainguard
    username: trainguard_user
    password: trainguard_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

strava:
  client-id: ${STRAVA_CLIENT_ID}
  client-secret: ${STRAVA_CLIENT_SECRET}
  refresh-token: ${STRAVA_REFRESH_TOKEN}
