spring:
  main:
    lazy-initialization: true
  application:
    name: trainguard-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

strava:
  client-id: ${STRAVA_CLIENT_ID}
  client-secret: ${STRAVA_CLIENT_SECRET}
  refresh-token: ${STRAVA_REFRESH_TOKEN}
  redirect-uri: ${STRAVA_REDIRECT_URI:http://localhost:8080/api/strava/callback}
  webhook:
    verify-token: ${STRAVA_WEBHOOK_VERIFY_TOKEN}
    subscription-id: ${STRAVA_WEBHOOK_SUBSCRIPTION_ID}
train-guard:
  app-redirect-uri: ${TRAIN_GUARD_APP_REDIRECT_URI:http://localhost:8081/strava-connected}
